---
title: "HOBOSensors"
author: html
editor: visual
---

#Load Libraries

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(seacarb)
library(broom)
library(readxl)
```

```{r}
pH1Data <- read_excel(here("Data/Tank_Data/HOBOSensors/22491059 2026-05-07 12_41_07 HST (Data HST).xlsx"))
pH2Data <- read_excel(here("Data/Tank_Data/HOBOSensors/22491060 2026-05-07 12_40_10 HST (Data HST).xlsx"))
pH3Data <- read_excel(here("Data/Tank_Data/HOBOSensors/22491061 2026-05-07 12_39_22 HST (Data HST).xlsx"))



CTDO1 <- read_csv(here("Data/Tank_Data/HOBOSensors/22482990 2026-05-07 11_10_57 HST (Data HST)(1).csv"))
CTDO2 <- read_csv(here("Data/Tank_Data/HOBOSensors/22482991 2026-05-07 12_37_06 HST (Data HST)(1).csv"))
```

Add a column to each pH data of the sensor serial number to identify from each other.

CTDO2

```{r}
# TrisCalpH1 <- TrisCalpH1 %>%
#   mutate(SensorNumber = "22491059") 
# TrisCalpH2 <- TrisCalpH2 %>%
#   mutate(SensorNumber = "22491060")
# TrisCalpH3 <- TrisCalpH3 %>%
#   mutate(SensorNumber = "22491061")

pH1Data <- pH1Data %>%
  mutate(SensorNumber = "22491059")
pH2Data <- pH2Data %>%
  mutate(SensorNumber = "22491060")
pH3Data <- pH3Data %>%
  mutate(SensorNumber = "22491061")

CTDO1 <- CTDO1 %>%
  mutate(SensorNumber = "22482990") %>%
  select(-1, -14:-18) %>%
  set_names("DateTime", "Temperature1", "MeasuredDO", "SalinityAdjustedDO", "Temperature2", "AbsolutePressure", "ElectricalConductivity", "SpecificConductivity", "Salinity", "TotalDissolvedSolids", "BarometricPressure","Depth", "SensorNumber" )

CTDO2 <- CTDO2 %>%
  mutate(SensorNumber = "22482291") %>%
    select(-1, -14:-18) %>%
  set_names("DateTime", "Temperature1", "AbsolutePressure", "ElectricalConductivity", "SpecificConductivity", "Salinity","TotalDissolvedSolids",  "Temperature2", "MeasuredDO", "SalinityAdjustedDO", "BarometricPressure", "Depth", "SensorNumber")
```

Combine all the TrisCal data to one dataframe and pH data

```{r}
# TrisCalData <- rbind(TrisCalpH1, TrisCalpH2, TrisCalpH3) %>%
#   select(-1,-6:-10) %>%
#   set_names("DateTime", "TrispH", "TrisTemperature", "TrisMillivolts", "SensorNumber" ) %>%
#   select(SensorNumber, everything()) %>%
#   mutate(DateTime = lubridate::mdy_hms(DateTime)) %>%
#   mutate(DateTime = floor_date(DateTime ,"min")) %>%
#   mutate(TrisDate = lubridate::ymd("2026-04-13")) %>%
#   drop_na()

  
pHData <- rbind(pH1Data, pH2Data, pH3Data) %>%
    select(-1) %>%
  set_names("DateTime", "pH", "Temperature", "Millivolts", "SensorNumber" ) %>%
  select(SensorNumber, everything()) %>%
  mutate(DateTime = lubridate::ymd_hms(DateTime)) %>%
    mutate(DateTime = floor_date(DateTime ,"min")) %>%
  #add a column of the location of the sensor was for each date times
  mutate(Location = case_when(DateTime >= ymd_hm("2026-05-04 11:05") & DateTime <= ymd_hm("2026-05-04 12:15") ~ "TrisCal", 
                              DateTime >= ymd_hm("2026-05-04 13:45") & DateTime <= ymd_hm("2026-05-05 15:25") ~ "CrossCal", 
                              DateTime >= ymd_hm("2026-05-05 15:30") & DateTime <= ymd_hm("2026-05_06 07:45") ~ "HIMBDock", 
                              DateTime >= ymd_hm("2026-05-06 11:00") & DateTime <= ymd_hm("2026-05-07 09:30") ~ "SamPan",
                              TRUE ~ "NA")) %>%
  filter(Location != "NA" ) %>%
  filter(pH < 8.5 & pH > 7.0)
    

## Create seperate dataframes for Tris Cal and each deployment 

TrisCalData <- pHData %>% filter(Location == "TrisCal") %>%
  set_names("SensorNumber","DateTime", "TrispH", "TrisTemperature", "TrisMillivolts", "Location"  ) %>% 
  mutate(TrisDate = lubridate::ymd("2026-05-04"))



CTDOData <- rbind(CTDO1, CTDO2) %>%
  select(SensorNumber, everything()) %>%
   mutate(DateTime = lubridate::mdy_hms(DateTime)) %>%
    mutate(DateTime = floor_date(DateTime ,"min")) %>%
  mutate(Location = case_when(DateTime >= ymd_hm("2026-05-04 13:45") & DateTime <= ymd_hm("2026-05-05 15:25") ~ "CrossCal", 
                              DateTime >= ymd_hm("2026-05-05 15:30") & DateTime <= ymd_hm("2026-05_06 07:45") ~ "HIMBDock", 
                              DateTime >= ymd_hm("2026-05-06 11:00") & DateTime <= ymd_hm("2026-05-07 09:30") ~ "SamPan" ,
                              TRUE ~ "NA")) %>%
  filter(Location != "NA")

Sal <- CTDOData %>% select(DateTime, Salinity)

pH_Salinity <- left_join(pHData, Sal, by = "DateTime", relationship = "many-to-many") %>% mutate(TrisDate = lubridate::ymd("2026-05-04")) %>%
    drop_na() 
```

```{r}
## take the mV calibration files by each date and use them to calculate pH
pHSlope<-TrisCalData %>%
  dplyr::nest_by(TrisDate, SensorNumber) %>%
  dplyr::mutate(fitpH = list(lm(TrisMillivolts~TrisTemperature, data = TrisCalData))) %>% # linear regression of mV and temp of the tris
  
  reframe(broom::tidy(fitpH)) %>% # make the output tidy
  select(TrisDate, SensorNumber, term, estimate) %>%
  pivot_wider(names_from = term, values_from = estimate) %>%# put slope and intercept in their own column

  left_join(pH_Salinity,.,by = c("TrisDate", "SensorNumber")) %>% # join with the pH sample data
  
 # separate(DateTime,sep=" ",into=c('date','time')) %>%
  #fill('(Intercept)',TrisTemperature) %>%
  #drop_na() %>%
  mutate(TrisMillivolts = Temperature*TrisTemperature + `(Intercept)`) %>% # calculate the mV of the tris at temperature in which the pH of samples were measured
  drop_na() %>%
  mutate(pHT = pH(Ex=Millivolts,Etris=TrisMillivolts,S=Salinity,T=Temperature)) %>% # calculate pH of the samples using the pH seacarb function
  #mutate(pH_insitu = pHinsi(pH = pH, ALK = TA_Raw, Tinsi = TempInSitu, Tlab = Temp, S = Salinity_lab_Silbiger)) %>%
  select(DateTime,SensorNumber,pHT) # ,Salinity_lab ## need to calculate pH insi then it is done
 # unite(date,c(date,time),sep=" ")

View(pHSlope)

pH_HOBO <- left_join(pHData, pHSlope, by = c("DateTime", "SensorNumber"))
```

```{r}

ggplot(pH_HOBO, aes(DateTime, pHT, group_by = "SensorNumber", color = SensorNumber)) +
  geom_point() +
 
   facet_wrap(~Location, scales = "free") +
     scale_x_datetime(date_breaks = "6 hours") +


     theme(axis.text.x = element_text(angle = 45, hjust = 1))
 
  ggsave(here("Output","pHTPlot_Hobos.png"), 
            width =12, height =6)
 
```

```{r}

pHPlot <- ggplot(pH_HOBO, aes(DateTime, pH, group_by = "SensorNumber", color = SensorNumber)) +
  geom_point() +
  facet_wrap(~Location, scales = "free") +

 
  scale_x_datetime(date_breaks = "6 hours") +
     theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
 pHPlot

  # pHPlot <- pHP +  
  # geom_point(data =OrionData, color = "blue", size =2) 
  # pHPlot
  # 
   ggsave(here("Output","pHPlot_Hobos.png"), 
            width =12, height =6)
```

```{r}
pH1 <- pH_HOBO %>% filter(SensorNumber == "22491059") %>% select(DateTime,Temperature, pHT) %>% rename(pH1 = pHT, Temp1 = Temperature) 
pH2 <- pH_HOBO %>% filter(SensorNumber == "22491060") %>% select(DateTime,Temperature, pHT) %>% rename(pH2 = pHT, Temp2 = Temperature)
pH3 <- pH_HOBO %>% filter(SensorNumber == "22491061") %>% select(DateTime,Temperature, pHT) %>% rename(pH3 = pHT, Temp3 = Temperature) 

pH_Subtract <- pH1 %>% 
  left_join(pH2, by = "DateTime") %>%
  left_join(pH3, by = "DateTime")

pH_Subtract <- pH_Subtract %>% mutate(pH12 = pH1 - pH2, pH13 = pH1 - pH3, pH23 = pH2 - pH3) %>% mutate(Temp12 = Temp1 - Temp2, Temp13 = Temp1 - Temp3, Temp23 = Temp2 - Temp3)

ggplot(pH_Subtract) +
  geom_point(aes(DateTime, pH12, color = "red")) +
  geom_point(aes(DateTime, pH13, color = "blue")) +
  geom_point(aes(DateTime, pH23, color = "green"))

ggplot(pH_Subtract) +
  geom_point(aes(DateTime, Temp12, color = "red")) +
  geom_point(aes(DateTime, Temp13, color = "blue")) +
  geom_point(aes(DateTime, Temp23, color = "green"))
```

```{r}
DOPlot <- ggplot(CTDOData, aes(DateTime, SalinityAdjustedDO, group_by = "SensorNumber", color = SensorNumber)) +
  geom_point() +
   facet_wrap(~Location, scales = "free") +
   scale_x_datetime(date_breaks = "6 hours") +
     theme(axis.text.x = element_text(angle = 45, hjust = 1))
DOPlot


  
  ggsave(here("Output","DOPlot_Hobos_Orion.png"), 
            width =12, height =6)

```

```{r}
DO1 <- CTDOData %>% filter(SensorNumber == "22482990") %>% select(DateTime,Temperature1, SalinityAdjustedDO) %>% rename(DO1 = SalinityAdjustedDO) 
DO2 <- CTDOData %>% filter(SensorNumber == "22482291") %>% mutate(DateTime = DateTime + minutes(1)) %>% select(DateTime,Temperature2, SalinityAdjustedDO) %>% rename(DO2 = SalinityAdjustedDO)
DO_Subtract <- left_join(DO1, DO2, by = "DateTime")

DO_Subtract <- DO_Subtract %>% mutate(DO_dif = DO1 - DO2) %>% mutate(Temp_dif = Temperature1 - Temperature2)

ggplot(DO_Subtract, aes(DateTime, DO_dif)) +
  geom_point()

ggplot(DO_Subtract, aes(DateTime, Temp_dif)) +
  geom_point()
```

```{r}
TemperaturePlot1 <- ggplot(CTDOData, aes(DateTime, Temperature1, group_by = "SensorNumber", color = SensorNumber)) +
  geom_point() +
    facet_wrap(~Location, scales = "free") +
  scale_x_datetime(date_breaks = "6 hours") +
     theme(axis.text.x = element_text(angle = 45, hjust = 1))
TemperaturePlot1

  
ggsave(here("Output","TemperaturePlot_Hobos_Orion.png"), 
            width =12, height =6)
```

```{r}
SalinityP <- ggplot(CTDOData, aes(DateTime, Salinity, group_by = "SensorNumber", color = SensorNumber)) +
  geom_point() +
  facet_wrap(~Location, scales = "free") +
    scale_x_datetime(date_breaks = "6 hours") +
     theme(axis.text.x = element_text(angle = 45, hjust = 1))
SalinityP


ggsave(here("Output","SalinityPlot_Hobos_Orion.png"), 
            width =12, height =6)
```

```{r}
ggplot(CTDOData, aes(DateTime, Depth, group_by = "SensorNumber", color = SensorNumber)) +
  geom_point() +
  facet_wrap(~Location, scales = "free") +
      scale_x_datetime(date_breaks = "6 hours") +
     theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(here("Output", "DepthPlot_HOBOS.png"), 
       width = 12, height =6)
```

The `echo: false` option disables the printing of code (only output is displayed).

mutate(Date = lubridate::ymd(Date)) %\>% filter(between(Date, ymd("2025-08-01"), ymd("2025-08-15"))) %\>%

```{r}
MiniDotData <- full_join(MiniDot1, MiniDot2)
DoCTDData <- full_join(DO2, DO1)

DoData <- full_join(MiniDotData, DoCTDData, by = c("Instrument","Tank", "DateTime", "DO", "Temperature")) 
  
DoDataFilter <- DoData %>% mutate(DateTime = lubridate::mdy_hm(DateTime)) %>%
  filter(between(DateTime,mdy_hm("03-17-2026 16:00"), mdy_hm("03-19_26 09:30")))


pHData <- rbind(pH1, pH2) 
phDataFilter <- pHData %>% mutate(DateTime = lubridate::mdy_hm(DateTime)) %>%
  filter(between(DateTime,mdy_hm("03-17-2026 16:00"), mdy_hm("03-19_26 09:30")))



```

```{r}
OrionData <- data.frame(DateTime = c(mdy_hm("03-18-2026 12:43","03-18-2026 20:29" , "03-18-2026 12:52","03-18-2026 20:39" )), 
              DO =c(8.16, 6.57, 6.64, 6.4), 
              Tank = c("Tank24", "Tank24", "Sump5", "Sump5")
                        )

pHOrionData <- data.frame(DateTime = c(mdy_hm("03-18-2026 12:43","03-18-2026 20:29" , "03-18-2026 12:52","03-18-2026 20:39" )), 
                          pH = c(8.16, 8.09, 8.11, 8.07), 
                          Millivolts = c(-66.6, -61.9, -62.9, -60.6), 
                          Tank = c("Tank24", "Tank24", "Sump5", "Sump5"))
```

```{r}
p1<- ggplot(DoDataFilter, aes(DateTime, DO, group_by = "Instrument", color = Instrument)) +
  geom_point() +
  facet_wrap(~Tank) 
   # annotate( "point",
   #         x = mdy_hm("03-18-2026 12:43"), 
   #         y = 7.01, 
   #         size =8,
   #         color = "blue") +
   # annotate( "point",
   #         x = mdy_hm("03-18-2026 20:29"), 
   #         y = 6.57, 
   #         size =8,
   #         color = "blue")
  
DOPlot <- p1 +
  geom_point(data =OrionData, color = "blue", size =7)

ggsave(here("Output","DOPlot.png"), 
            width =9, height =6)
```

```{r}
 p2 <- ggplot(phDataFilter, aes(DateTime, pH, group_by = "Instrument", color = Instrument)) +
  geom_point() +
  facet_wrap(~Tank) 
 
 pHPlot <- p2 +  
  geom_point(data =pHOrionData, color = "blue", size =2)
 
 ggsave(here("Output","pHPlot.png"), 
            width =9, height =6)
```

```{r}
 p3 <- ggplot(phDataFilter, aes(DateTime, Millivolts, group_by = "Instrument", color = Instrument)) +
  geom_point() +
  facet_wrap(~Tank) 
   
    MillivoltPlot <- p3 + geom_point(data =pHOrionData, color = "blue", size =2)
    
    ggsave(here("Output","MillivoltPlot.png"), 
            width =9, height =6)
    
    

```

```{r}

 ggplot(DoCTDData, aes(DateTime, Salinity, group_by = "Instrument", color = Instrument)) +
  geom_point() 

g
```

```{r}

MiniDotData <- full_join(MiniDot1, MiniDot2)
CTDOData <- full_join(CTDDO1, CTDDO2)


  
CTDOData_Sump <- CTDOData %>% mutate(Date_Time = lubridate::mdy_hm(Date_Time)) %>%
  filter(between(Date_Time,mdy_hm("03-27-2026 20:00"), mdy_hm("04-06_26 09:00")))


pHData <- rbind(pH1, pH2) 
phDataFilter <- pHData %>% mutate(Date_Time = lubridate::mdy_hm(Date_Time)) %>%
  filter(between(Date_Time,mdy_hm("03-27-2026 20:00"), mdy_hm("04-06_26 09:00")))

```

```{r}
CTDOOrionData <- data.frame(Date_Time = c(mdy_hm("03-30-2026 12:50","03-30-2026 20:44", "03-31-2026 12:27", "04-01-2026 12:46", "04-01-2026 20:47", "04-02-2026 12:35", "04-03-2026 13:21","04-04-2026 12:52", "04-05-2026 12:54", "04-06-2026 06:54")), 
              DO =c(7.39, 6.98, 7.18, 7.00, 6.63, 6.92, 7.18,7.24, 7.06, 6.58),
              Salinity =c(33.6 ,33.29 ,34.42,35.04, 34.91, 35.29, 33.178,33.72, 33.91, 34.14), 
              pH = c( 8.16, 8.14, 8.11 ,8.14, 8.14, 8.14, 8.17,8.18, 8.14, 8.10),
              Temperature1 = c(24.962 ,24.447 ,24.917, 24.714,24.378, 24.758, 24.071, 25.733,24.722, 24.407))
```

```{r}
DOPlot1 <- ggplot(CTDOData_Sump, aes(Date_Time, DO, group_by = "Instrument", color = Instrument)) +
  geom_point() +
  scale_x_datetime(date_breaks = "6 hours") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
DOPlot1 +
  geom_point(data =CTDOOrionData, color = "blue", size =5)

 ggsave(here("Output","DOPlot.png"), 
            width =12, height =6)
```

```{r}
 SalinityPlot <- ggplot(CTDOData_Sump, aes(Date_Time, Salinity, group_by = "Instrument", color = Instrument)) +
  geom_point() +
   scale_x_datetime(date_breaks = "6 hours") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 
SalinityPlot +
  geom_point(data =CTDOOrionData, color = "blue", size =5)

 ggsave(here("Output","SalinityPlot.png"), 
            width =12, height =6)
```

```{r}

 ggplot(CTDOData_Sump, aes(Date_Time, Pressure, group_by = "Instrument", color = Instrument)) +
  geom_point() +
      scale_x_datetime(date_breaks = "6 hours") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 
  ggsave(here("Output","PressurePlot.png"), 
            width =12, height =6)
```

```{r}

 pHPlot <- ggplot(phDataFilter, aes(Date_Time, pH, group_by = "Instrument", color = Instrument)) +
  geom_point() +
      scale_x_datetime(date_breaks = "6 hours") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 
 pHPlot + 
  geom_point(data =CTDOOrionData, color = "blue", size =5)
  ggsave(here("Output","pHPlot.png"), 
            width =12, height =6)
```

```{r}
TempPlot <- ggplot(CTDOData_Sump, aes(Date_Time, Temperature1, group_by = "Instrument", color = Instrument)) +
  geom_point() +
  scale_x_datetime(date_breaks = "6 hours") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  TempPlot
TempPlot +
  geom_point(data =CTDOOrionData, color = "blue", size =5)

 ##width =12, height =6)
```
